### ISSUE TITLE
Optional and ParamArray rules not implemented

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#161]
**Describe the bug**
As stated [here](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/sub-statement):  
>**Optional**. Keyword indicating that an argument is not required. If used, all subsequent arguments in *arglist* must also be optional and declared by using the **Optional** keyword. **Optional** can't be used for any argument if **ParamArray** is used.

>**ParamArray**. Used only as the last argument in _arglist_ to indicate that the final argument is an **Optional**  [array](https://docs.microsoft.com/en-gb/office/vba/language/glossary/vbe-glossary#array) of **Variant** elements. The **ParamArray** keyword allows you to provide an arbitrary number of arguments. **ParamArray** can't be used with **ByVal**, **ByRef**, or **Optional**.

**To Reproduce**
```VBA
Module Test
    Public Sub Main()
        TestParam1 1, 2, 3
        ' TestParam2 2, 3, 4 'This does not compile but the method does
        TestParam3 3, 4, 5
    End Sub
    
    Public Sub TestParam1(ByVal arg1 As Long, Optional ByVal arg2 As Long = 1, ByVal arg3 As Long)
        MsgBox "Arguments: " & Join(Array(arg1, arg2, arg3),", ")
    End Sub
    
    Public Sub TestParam2(ByVal ParamArray args() As Variant, Optional ByVal arg1 As Long = 1)
        MsgBox "Argument: " & arg1
    End Sub
    
    Public Sub TestParam3(Optional ByVal arg1 As Long = 1, ByRef ParamArray args() As Variant)
        MsgBox "Argument: " & arg1
    End Sub
End Module
```

**Expected behavior**
```TestParam1``` should not allow non-optional parameters after the first optional parameter.
```TestParam2``` should not allow any other parameters after ```ParamArray``` .
```TestParam2``` and  ```TestParam3``` should not allow both the ```Optional``` and ```ParamArray``` keywords to be used in the same method definition. ```ParamArray``` should not be allowed together with ```ByVal``` or ```ByRef```. 

None of the ```TestParamX``` methods should compile. 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.9.2720

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
Thanks.  You're right, these are understood and implemented, but not validated properly to prevent incorrect usage.

**Comment by cristianbuse** [comment]
One more case to add to this:  
```VBA
Module Test
    Public Sub Main()
        TestType Nothing, Nothing, Nothing
    End Sub

    Public Sub TestType(ParamArray arr() As String)
        MsgBox Ubound(arr)
    End Sub
End Module
```

As you mentioned, the keyword is understood, and the above works as if the array was declared as Variant. It's just the compile part that needs to enforce the type as ```Variant```.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.509, thanks for reporting

**Comment by cristianbuse** [comment]
The following 2 are still an issue as we can't have both Keywords in same definition:  
```VBA
    Public Sub TestParam2(ParamArray args() As Variant, Optional ByVal arg1 As Long = 1)
        MsgBox "Argument: " & arg1
    End Sub
    
    Public Sub TestParam3(Optional ByVal arg1 As Long = 1, ParamArray args() As Variant)
        MsgBox "Argument: " & arg1
    End Sub
```

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.540, thanks!
