### ISSUE TITLE
Another editor crash

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#218]
**Describe the bug**
Editor crashed during code edit leaving twinbasic in a non restartable (by me anyway) condition.

Project is attached.  The error occurred in the Types Class whilst editing the IsCountZero overloads.

[twinBASIC_VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6643597/twinBASIC_VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Apologies, this was a recent regression, fixed in v0.10.1455

**Comment by FullValueRider** [comment]
My recollection is that the last time I encountered this issue you needed to do two fixes.  Unfortunately the  v0.10.1455 update is still showing issues so could there be an additional fix that is required?

**Comment by WaynePhillipsEA** [comment]
Seems to open OK in v0.10.1455 here. Is it not opening at all for you?

**Comment by FullValueRider** [comment]
Hi Wayne

It opens fine and the editing issues I had with the IsZeroCount overload
were resolved and that set of edits completed ok. Twinbasic started
flagging save errors when I started adding overloads to the types.convertor
method to eliminate the case statement.

mangled by mobile

**Comment by FullValueRider** [comment]
Attached is the updated code which is showing a compiler error.  The Types class cannot be saved.

[twinBASIC_VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6646371/twinBASIC_VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks - repro'd in v0.10.1455, but not on my latest build (not released), so I'll assume already fixed in the next release that should land in the next hour or so.

**Comment by WaynePhillipsEA** [comment]
So this should be all fixed in the latest builds.   In the very latest v0.10.1619 build I've fixed the VS code extension so that it does now put the compiler into 'DISABLED' mode when a hard-crash keeps occurring.  Previous builds were supposed to be doing that, but it wasn't working.

So now, you may still get the 'Unable to write to file' error when a hard crash occurs, but as soon as the twinBASIC crash alert prompt comes up, that file error should disappear, and you'll be in **_disabled_** mode.  In **_disabled_** mode you can get into your project files and make edits or revert the last changes, with the hope that you'll save the project in a working state so that you can re-open it normally (or right click on the win32 build configuration and press RELOAD).

I appreciate the hard-crashing is not particularly good user experience, and more focus will go into this area soon once we're roughly at feature parity with VB6 / VBA.
