### ISSUE TITLE
Description doesn't display correctly in VBA object browser

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#822]
**Describe the bug**
For some reason, I get gibberish numbers instead of meaningful description in VBA's OB.
![image](https://user-images.githubusercontent.com/2367644/166174844-63752fbc-da52-42d9-9aae-3ebc263c412a.png)

**To Reproduce**
1. Create an ActiveX DLL project
2. Create a class, expose a method and add a `Description` attribute to the method
3. Build the DLL
4. Open 64-bit Excel and reference the built- DLL. 
5. Open the VBA OB and go to the class' method. See a number instead.

**Expected behavior**
The description should display normally.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE Beta 28

**Comment by lunasoft2001** [comment]
I'm corious to see what are you supongo with this dll. 🤓

**Comment by bclothier** [comment]
@lunasoft2001  [you can read more about it or even contribute here](https://github.com/bclothier/TwinBasicSevenZip).

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 29, thanks for reporting!

**Comment by bclothier** [comment]
FYI, this seems to have recurred. I can see the description just fine on the classes but still get the numbers on the class members.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 39, thanks!
